# Generated by Django 5.0.6 on 2025-01-11 21:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TreePlanting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Region', models.CharField(choices=[('Mau', 'Mau'), ('Aberdare', 'Aberdare'), ('Mt. Kenya', 'Mt. Kenya'), ('Cherangany hills', 'Cherangany hills'), ('Mt. Elgon', 'Mt. Elgon')], default='Mau', max_length=50)),
                ('County', models.CharField(choices=[('Kiambu', 'Kiambu'), ("Murang'a", "Murang'a"), ('Nyeri', 'Nyeri'), ('Mombasa', 'Mombasa'), ('Kwale', 'Kwale'), ('Kilifi', 'Kilifi'), ('Nairobi', 'Nairobi'), ('Nakuru', 'Nakuru'), ('Bomet', 'Bomet'), ('Kericho', 'Kericho'), ('Trans-Nzoia', 'Trans-Nzoia'), ('Bungoma', 'Bungoma'), ('Kakamega', 'Kakamega'), ('Vihiga', 'Vihiga'), ('Homa Bay', 'Homa Bay'), ('Kisii', 'Kisii'), ('Migori', 'Migori'), ('Meru', 'Meru'), ('Embu', 'Embu'), ('Kitui', 'Kitui'), ('Garissa', 'Garissa'), ('Wajir', 'Wajir'), ('Mandera', 'Mandera')], max_length=50)),
                ('Subcounty', models.CharField(choices=[('Thika', 'Thika'), ('Ruiru', 'Ruiru'), ("Murang'a South", "Murang'a South"), ("Murang'a North", "Murang'a North"), ('Mombasa Town', 'Mombasa Town'), ('Likoni', 'Likoni'), ('Kinango', 'Kinango'), ('Lunga Lunga', 'Lunga Lunga'), ('Naivasha', 'Naivasha'), ('Nakuru', 'Nakuru'), ('Gilgil', 'Gilgil'), ('Homa Bay Town', 'Homa Bay Town'), ('Rachuonyo South', 'Rachuonyo South')], max_length=50)),
                ('Field_id', models.CharField(max_length=20)),
                ('Entry_number', models.IntegerField()),
                ('Date_collected', models.DateField(default=django.utils.timezone.now)),
                ('Location', models.CharField(max_length=255)),
                ('Tree_species', models.CharField(max_length=100)),
                ('Field_size', models.FloatField()),
                ('Trees_planted', models.IntegerField()),
            ],
        ),
    ]
