# Generated by Django 5.1.4 on 2025-01-14 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoreapp', '0002_testplanting'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestPlanting',
        ),
    ]
