# Generated by Django 5.1.4 on 2025-01-14 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoreapp', '0003_delete_testplanting'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TreePlanting',
            new_name='TreeData',
        ),
    ]
