# Generated by Django 5.1.4 on 2025-01-14 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoreapp', '0004_rename_treeplanting_treedata'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TreeData',
            new_name='TreeDataEntry',
        ),
    ]
