# Generated by Django 5.1.4 on 2025-01-14 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreapp', '0005_rename_treedata_treedataentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='treedataentry',
            name='carbon_sequestration',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='treedataentry',
            name='soil_health_improvement',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='treedataentry',
            name='tree_cover_increase',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='treedataentry',
            name='wildlife_habitat_conservation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
